# Generated by Django 3.2.9 on 2021-11-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MyName', models.CharField(max_length=500)),
                ('MyBirthday', models.DateField()),
                ('MyInformation', models.TextField()),
                ('MyPhoto', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('BlogId', models.AutoField(primary_key=True, serialize=False)),
                ('BlogName', models.CharField(max_length=500)),
                ('BlogContent', models.TextField()),
                ('BlogPhoto', models.CharField(max_length=500)),
            ],
        ),
    ]
