# Generated by Django 3.2.9 on 2021-11-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutme',
            name='id',
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='MyName',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
    ]
